name: Semgrep

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/php
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v5
      - name: Semgrep PHP rules
        run: semgrep scan --config p/php --error --metrics=off
